"""add secondary indexes

Revision ID: 0193202de7ca
Revises: acb828cc2c29
Create Date: 2026-05-01 11:39:24.877345

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0193202de7ca"
down_revision: str | Sequence[str] | None = "acb828cc2c29"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_handoff_summaries_doctor_user_id"),
        "handoff_summaries",
        ["doctor_user_id"],
        unique=False,
        postgresql_where=sa.text("doctor_user_id IS NOT NULL"),
    )
    op.create_index(op.f("ix_kb_chunks_language"), "kb_chunks", ["language"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kb_chunks_language"), table_name="kb_chunks")
    op.drop_index(op.f("ix_handoff_summaries_doctor_user_id"), table_name="handoff_summaries")
    # ### end Alembic commands ###
