"""add account lockout fields

Revision ID: 7774aebfe2b0
Revises: 0193202de7ca
Create Date: 2026-05-01 11:51:38.166597

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7774aebfe2b0"
down_revision: str | Sequence[str] | None = "0193202de7ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("failed_login_attempts", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "locked_until")
    op.drop_column("users", "failed_login_attempts")
    # ### end Alembic commands ###
