"""
PDF Generation — توليد ملفات PDF باستخدام WeasyPrint

بيحول محتوى markdown (أو HTML) لملف PDF احترافي.
بنسخدم WeasyPrint عشان التحويل من HTML → PDF بشكل دقيق.
"""

from __future__ import annotations

import re

from app.core.config import settings


def markdown_to_html(md: str, title: str = "MedAgent Handoff Summary") -> str:
    """تحويل markdown لـ HTML جاهز للـ PDF."""
    # تحويل العناوين
    md = re.sub(r"^#### (.+)$", r"<h4>\1</h4>", md, flags=re.MULTILINE)
    md = re.sub(r"^### (.+)$", r"<h3>\1</h3>", md, flags=re.MULTILINE)
    md = re.sub(r"^## (.+)$", r"<h2>\1</h2>", md, flags=re.MULTILINE)
    md = re.sub(r"^# (.+)$", r"<h1>\1</h1>", md, flags=re.MULTILINE)

    # تنسيق النص
    md = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", md)
    md = re.sub(r"\*(.+?)\*", r"<em>\1</em>", md)
    md = re.sub(r"`([^`]+)`", r"<code>\1</code>", md)

    # القوائم
    md = re.sub(r"^- (.+)$", r"<li>\1</li>", md, flags=re.MULTILINE)
    md = re.sub(r"(<li>.*?</li>\n?)+", r"<ul>\g<0></ul>", md)

    # الفقرات
    paragraphs = md.split("\n\n")
    html_paragraphs = []
    for p in paragraphs:
        p = p.strip()
        if not p:
            continue
        if p.startswith("<h") or p.startswith("<ul") or p.startswith("<li"):
            html_paragraphs.append(p)
        else:
            html_paragraphs.append(f"<p>{p}</p>")

    body = "\n".join(html_paragraphs)

    # RTL support for Arabic content
    direction = "rtl" if _has_arabic(md) else "ltr"

    return f"""<!DOCTYPE html>
<html lang="{"ar" if direction == "rtl" else "en"}" dir="{direction}">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&family=Inter:wght@400;600;700&display=swap');
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: 'Inter', 'Cairo', sans-serif;
    font-size: 12pt;
    line-height: 1.8;
    color: #1e3544;
    max-width: 800px;
    margin: 0 auto;
    padding: 40px 50px;
  }}
  h1 {{ font-size: 22pt; color: #005bc0; margin-bottom: 16px; border-bottom: 2px solid #005bc0; padding-bottom: 8px; }}
  h2 {{ font-size: 16pt; color: #004fa9; margin-top: 28px; margin-bottom: 12px; }}
  h3 {{ font-size: 13pt; color: #4b6273; margin-top: 20px; margin-bottom: 8px; }}
  h4 {{ font-size: 11pt; color: #4b6273; margin-top: 16px; margin-bottom: 6px; }}
  p {{ margin-bottom: 10px; }}
  ul {{ margin: 10px 0 10px 24px; }}
  li {{ margin-bottom: 4px; }}
  strong {{ color: #1e3544; }}
  code {{ background: #ebf5ff; padding: 2px 6px; border-radius: 4px; font-size: 10pt; }}
  .disclaimer {{
    margin-top: 40px;
    padding: 16px;
    background: #fff3cd;
    border: 1px solid #ffc107;
    border-radius: 12px;
    font-size: 10pt;
    color: #856404;
  }}
  .header-brand {{
    text-align: center;
    margin-bottom: 32px;
    padding-bottom: 16px;
    border-bottom: 1px solid #e1f0fe;
  }}
  .header-brand h1 {{ font-size: 28pt; color: #005bc0; border-bottom: none; margin-bottom: 4px; }}
  .header-brand p {{ color: #4b6273; font-size: 10pt; }}
  .meta {{ font-size: 9pt; color: #9eb5c8; margin-top: 40px; text-align: center; }}
</style>
</head>
<body>
<div class="header-brand">
  <h1>MedAgent</h1>
  <p>Bilingual Medical Triage Assistant — Doctor Handoff Summary</p>
</div>
{body}
<div class="disclaimer">
  <strong>⚠️ Medical Disclaimer:</strong> This document was generated by an AI system as a preliminary
  assessment tool. It is NOT a substitute for professional medical diagnosis, treatment, or clinical
  judgment. Always consult a licensed physician. The information herein is grounded in retrieved medical
  guidelines and should be used only as a chart prep aid by qualified clinicians.
</div>
<div class="meta">
  Generated by MedAgent v{settings.VERSION} | Environment: {settings.ENV}<br>
  This document contains Protected Health Information (PHI) — handle in accordance with applicable privacy regulations.
</div>
</body>
</html>"""


async def generate_pdf(html_content: str) -> bytes:
    """
    يولد PDF من HTML باستخدام WeasyPrint.

    Args:
        html_content: HTML جاهز

    Returns:
        bytes: محتوى PDF

    Raises:
        ImportError: لو weasyprint مش مثبت
    """
    try:
        from weasyprint import HTML
    except ImportError as e:
        raise ImportError(
            "weasyprint is required for PDF generation. Install it with: uv add weasyprint"
        ) from e

    pdf_bytes = HTML(string=html_content).write_pdf()
    return pdf_bytes


def _has_arabic(text: str) -> bool:
    """بيكشف لو النص فيه حروف عربية."""
    return bool(re.search(r"[\u0600-\u06FF\u0750-\u077F]", text))
