"""
Export Agent - Generates validated, professional medical reports in PDF format.
Includes cryptographic signatures (Audit Hashes) and security watermarks.
"""

import json
import logging
from datetime import datetime

from fpdf import FPDF

from agents.governance_agent import GovernanceAgent

logger = logging.getLogger(__name__)


class ExportAgent:
    """
    Agent for generating secure, formatted medical reports.
    """

    def __init__(self):
        self.governance = GovernanceAgent()

    def generate_patient_summary_pdf(
        self, patient_profile: dict, interactions: list, file_path: str
    ):
        """
        Create a comprehensive PDF report for a patient.
        """
        try:
            pdf = FPDF()
            pdf.add_page()

            # Header
            pdf.set_font("helvetica", "B", 16)
            pdf.cell(0, 10, "MedAgent Clinical Summary Report", ln=True, align="C")
            pdf.set_font("helvetica", "I", 10)
            pdf.cell(
                0,
                10,
                f"Generated on: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC",
                ln=True,
                align="C",
            )
            pdf.ln(10)

            # Patient Info
            pdf.set_font("helvetica", "B", 12)
            pdf.cell(0, 10, "Patient Information", ln=True)
            pdf.set_font("helvetica", "", 10)
            pdf.cell(0, 8, f"Patient ID: {patient_profile.get('id', 'N/A')}", ln=True)
            pdf.cell(
                0,
                8,
                f"Age: {patient_profile.get('age', 'N/A')} | Gender: {patient_profile.get('gender', 'N/A')}",
                ln=True,
            )
            pdf.ln(5)

            # Summary Table
            pdf.set_font("helvetica", "B", 12)
            pdf.cell(0, 10, "Consultation History", ln=True)

            pdf.set_font("helvetica", "B", 10)
            pdf.cell(40, 8, "Date", border=1)
            pdf.cell(100, 8, "Diagnosis / Reasoning", border=1)
            pdf.cell(50, 8, "Audit Hash", border=1)
            pdf.ln()

            pdf.set_font("helvetica", "", 9)
            for inter in interactions:
                date_str = inter.get("timestamp", "").split("T")[0]
                diag = (
                    inter.get("diagnosis", "N/A")[:100] + "..."
                    if len(inter.get("diagnosis", "")) > 100
                    else inter.get("diagnosis", "N/A")
                )
                ahash = inter.get("audit_hash", "N/A")[:15] + "..."

                pdf.cell(40, 8, date_str, border=1)
                pdf.cell(100, 8, diag, border=1)
                pdf.cell(50, 8, ahash, border=1)
                pdf.ln()

            # Footer & Security
            pdf.ln(20)
            pdf.set_font("helvetica", "I", 8)
            pdf.multi_cell(
                0,
                5,
                "This report is generated by MedAgent Clinical Orchestrator. The findings presented are for guidance only and should be reviewed by a certified medical professional. The Audit Hashes above can be verified against the secure system logs for data integrity.",
            )

            # Final signature of the whole report
            try:
                report_hash = self.governance.sign_evidence(json.dumps(interactions))
                pdf.ln(5)
                pdf.set_font("helvetica", "B", 8)
                pdf.cell(
                    0, 10, f"Full Report Integrity Signature: {report_hash}", ln=True
                )
            except Exception:
                pass

            pdf.output(file_path)
            return True
        except Exception as e:
            logger.error(f"Failed to generate PDF: {e}")
            return False
